language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: m1/TJVHBEPbmVS5VP/HumG2a/TpxSF1n1f6wLdv2kxAUPnb3CbfHhYf0TI51iZeJDLIJW0Tpvvu2c+mjsfvsNniS2/j7x6NZjxqjegsHTfEcdMAz69Lf73YzLlLhldVeTuXU3lAblRZdDWbhT56UlR7rvGraRYNycpx0mCTQQkkndN0bKMz7Mnyp/uzI7QdN5NGwKt3D/GD2qVEajjG8ln0qfZMzvFRwy4sQydJELrLxJgGoefhC7MqWv7iwQHsmH77bLFT5/KZQ3SWJgxIHYyHK6JzYg1j9FX3s/++Ct71T2S4juJD21vId/NvI51jVbZDVSqYyYwwx3pJoN6l7YzC/KYtZ048Q1mSXlfvRYkOXJyiwvRRjNGnSGJG34R2Qi3isJAOwHfC6Vwba6/8K+LddAYQXZTns4HY1yIMVw/wrz2k6t/EhwaFA5/JXefi28sqIGgGjxipQ2Ys6B3siZK0wx5TbEPc6O5TvGuGc0ENEJpWNJaIYrrJpkYvoliL5dlp0oKgcHM0s8t31hBi5UELKcyiuMq3G3ZxIC4W6j94GMXvroKgI/Kgi5XI2fyNXuOxJ1Q5aPWX/DwTrAar3hTogwGKDey5V9dFapMfCZrpKjTUUAA9ymj/J4AzI0NrI3znou7mOhPPXnrLjOHDDPGEPokL2GLT2094Aq1xkXp0=
  app: viewing-party-2008
  run: rails db:migrate
